# Generated by Django 6.0 on 2025-12-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_item_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=2001, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
